config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'pages#home'
  get 'the-scope', to: 'portfolios#misc'
  get 'other', to: 'portfolios#other'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end


  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
# == Schema Information
#
# Table name: portfolios
#
#  id          :integer          not null, primary key
#  title       :string
#  subtitle    :string
#  body        :text
#  main_image  :text
#  thumb_image :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Portfolio < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :subtitle, :body, :main_image, :thumb_image

  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda{ |attr| attr['name'].blank? }
  def self.theScope
    where(subtitle: 'scope' )
  end
  scope :other_items_portfolio, -> { where(subtitle: 'other')}

  after_initialize :set_defaults

  private
  def set_defaults
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
  def index
    @portfolio_items = Portfolio.all
  end

  def misc
    @scope_portfolio_items = Portfolio.theScope
  end

  def other
    @other_portfolio_items = Portfolio.other_items_portfolio
  end

  def new
    @portfolio_item = Portfolio.new
    3.times {@portfolio_item.technologies.build}
  end

  def create
    @portfolio_item = Portfolio.new(item_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(item_params)
        format.html { redirect_to portfolios_path, notice: 'The portfolio item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio item was successfully removed.' }
    end
  end

  private
    def item_params
      params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <!-- <div class="field"> -->
    <!-- <%= f.label :main_image %>
    <%= f.text_area :main_image %>
  </div>

  <div class="field">
    <%= f.label :thumb_image %>
    <%= f.text_area :thumb_image %>
  </div> -->

  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio Item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio</h1>

<%= link_to "Creat new Item", new_portfolio_path %>

<% @portfolio_items.each do |item| %>
  <h3><%= link_to item.title, portfolio_show_path(item) %></h3>
  <p><%= item.subtitle %></p>
  <p><%= item.body %></p>
  <p><%= image_tag item.thumb_image unless item.thumb_image.nil?%></p>
  <%= link_to "Edit", edit_portfolio_path(item.id) %>
  <%= link_to 'Destroy', portfolio_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
  <hr>
<% end %>

app/views/portfolios/misc.html.erb
<h1>Scope Portfolio</h1>

<%= link_to "Creat new Item", new_portfolio_path %>

<% @scope_portfolio_items.each do |item| %>
  <h3><%= link_to item.title, portfolio_show_path(item) %></h3>
  <p><%= item.subtitle %></p>
  <p><%= item.body %></p>
  <p><%= image_tag item.thumb_image unless item.thumb_image.nil?%></p>
  <%= link_to "Edit", edit_portfolio_path(item.id) %>
  <%= link_to 'Destroy', portfolio_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
  <hr>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create New Portfolio Item</h1>
<% if @portfolio_item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@portfolio_item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
    <% @portfolio_item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/other.html.erb
<h1>Other Portfolio</h1>

<%= link_to "Creat new Item", new_portfolio_path %>

<% @other_portfolio_items.each do |item| %>
  <h3><%= link_to item.title, portfolio_show_path(item) %></h3>
  <p><%= item.subtitle %></p>
  <p><%= item.body %></p>
  <p><%= image_tag item.thumb_image unless item.thumb_image.nil?%></p>
  <%= link_to "Edit", edit_portfolio_path(item.id) %>
  <%= link_to 'Destroy', portfolio_path(item), method: :delete, data: { confirm: 'Are you sure?' } %>
  <hr>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>
<em><%= @portfolio_item.subtitle %></em>
<p><%= @portfolio_item.body %></p>

<h2>Technologies Used</h2>
<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>
<% end %>